- name: reload firewalld
  service: name=firewalld state=reloaded

- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: enable scxmppd service
  service: name=scxmppd enabled=yes
